;;; org-timeblock-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from org-timeblock.el

(autoload 'org-timeblock-list "org-timeblock" "\
Enter `org-timeblock-list-mode'." t)
(autoload 'org-timeblock "org-timeblock" "\
Enter `org-timeblock-mode'." t)
(register-definition-prefixes "org-timeblock" '("org-timeblock-"))

;;; End of scraped data

(provide 'org-timeblock-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-timeblock-autoloads.el ends here
