name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Framework13 NixOS image
        run: nix build .#nixosConfigurations.nixos.config.system.build.toplevel

      - name: Build Knosence home-manager profile
        run: nix build .#homeConfigurations.knosence.activationPackage

      - name: Flake check
        run: nix flake check

